spring:
  application:
    name: humtune
  datasource:
    url: jdbc:postgresql://localhost:5432/humtune
    username: humtune
    password: humtune
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
