spring:
  application:
    name: humtune
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/humtune}
    username: ${SPRING_DATASOURCE_USERNAME:humtune}
    password: ${SPRING_DATASOURCE_PASSWORD:humtune}
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
